//! A file's generated-content marker decides its role the same way in every
//! scan stage: project audits run after file text is dropped, so the marker
//! must be kept with the file's facts.

use serde_json::Value;
use std::fs;
use std::path::Path;
use std::process::Command;
use tempfile::tempdir;

const DEEP: &str = "packages/app/src/proto/v1/types";

fn write(root: &Path, path: &str, content: &str) {
    let path = root.join(path);
    fs::create_dir_all(path.parent().expect("parent")).expect("parent dir");
    fs::write(path, content).expect("write file");
}

fn nesting_findings(root: &Path) -> Vec<String> {
    let output = Command::new(env!("CARGO_BIN_EXE_repopilot"))
        .args(["scan", ".", "--profile", "strict", "--format", "json"])
        .current_dir(root)
        .output()
        .expect("scan runs");
    assert!(output.status.success(), "{output:?}");
    let report: Value = serde_json::from_slice(&output.stdout).expect("scan JSON");
    report["findings"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .iter()
        .filter(|finding| finding["rule_id"] == "architecture.deep-directory-nesting")
        .filter_map(|finding| finding["evidence"][0]["path"].as_str().map(str::to_string))
        .collect()
}

#[test]
fn a_generated_file_is_not_held_to_the_repository_layout() {
    let temp = tempdir().expect("temp repo");
    let root = temp.path();
    write(
        root,
        &format!("{DEEP}/messages.ts"),
        "// @generated by protoc-gen-ts. DO NOT EDIT.\nexport interface Message {\n  id: string;\n}\n",
    );
    write(
        root,
        &format!("{DEEP}/handwritten.ts"),
        "export function handle(id: string): string {\n  return id;\n}\n",
    );
    let flagged = nesting_findings(root);
    assert!(
        flagged.iter().any(|path| path.ends_with("handwritten.ts")),
        "the hand-written file is nested too deep: {flagged:?}"
    );
    assert!(
        !flagged.iter().any(|path| path.ends_with("messages.ts")),
        "the generated file's layout is its generator's: {flagged:?}"
    );
}

/// next.js templates set `description: "Generated by create next app"` in
/// their metadata. That string is the app's content, not a generator's mark:
/// only a header comment marks a file as generated.
#[test]
fn a_marker_phrase_in_code_is_not_a_generated_header() {
    let temp = tempdir().expect("temp repo");
    let root = temp.path();
    write(
        root,
        &format!("{DEEP}/layout.ts"),
        "export const metadata = {\n  title: \"Create Next App\",\n  description: \"Generated by create next app\",\n};\n",
    );
    write(
        root,
        &format!("{DEEP}/migration.py"),
        "# Generated by Django 4.2 on 2026-10-05 12:00\nfrom django.db import migrations\n",
    );
    let flagged = nesting_findings(root);
    assert!(
        flagged.iter().any(|path| path.ends_with("layout.ts")),
        "a phrase in a string literal is code: {flagged:?}"
    );
    assert!(
        !flagged.iter().any(|path| path.ends_with("migration.py")),
        "a header comment marks generated code: {flagged:?}"
    );
}
