use crate::findings::types::{Finding, FindingCategory, Severity};
use crate::output::vibe::VibeCategory;
use crate::rules::lookup_rule_metadata;
use crate::scan::types::ScanSummary;
use std::fmt::Write as FmtWrite;

pub struct HardenOptions {
    pub focus: Option<VibeCategory>,
    pub budget_tokens: usize,
}

impl Default for HardenOptions {
    fn default() -> Self {
        Self {
            focus: None,
            budget_tokens: 4096,
        }
    }
}

pub fn render(summary: &ScanSummary, opts: &HardenOptions) -> String {
    let project_name = summary
        .root_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("project");
    let budget_chars = opts.budget_tokens.saturating_mul(4);

    let mut findings: Vec<&Finding> = summary
        .findings
        .iter()
        .filter(|finding| {
            opts.focus
                .as_ref()
                .is_none_or(|focus| focus.matches(&finding.category))
        })
        .collect();
    findings.sort_by(|left, right| {
        priority_rank(left)
            .cmp(&priority_rank(right))
            .then_with(|| right.severity.cmp(&left.severity))
            .then_with(|| category_rank(&left.category).cmp(&category_rank(&right.category)))
            .then_with(|| left.rule_id.cmp(&right.rule_id))
            .then_with(|| finding_location_key(left).cmp(&finding_location_key(right)))
    });

    let mut out = String::new();
    let _ = writeln!(out, "# RepoPilot Harden Plan - {project_name}\n");
    let _ = writeln!(
        out,
        "Prioritized remediation plan generated locally from RepoPilot findings. Start at P0 and stop when the remaining risk is acceptable for this release.\n"
    );
    render_summary(&mut out, &findings);

    if findings.is_empty() {
        let _ = writeln!(out, "No findings matched the selected scope.");
        render_footer(&mut out, summary.scan_duration_us);
        return out;
    }

    let mut current_priority = None;
    let content_start = out.len();

    for (index, finding) in findings.into_iter().enumerate() {
        let priority = priority_label(finding);
        if current_priority != Some(priority) {
            let _ = writeln!(out, "\n## {priority}");
            current_priority = Some(priority);
        }

        let mut item = String::new();
        render_finding_plan(&mut item, finding, index + 1);
        if index > 0 && out.len().saturating_sub(content_start) + item.len() > budget_chars {
            let _ = writeln!(out, "\n*[Plan truncated to stay within token budget]*");
            break;
        }
        out.push_str(&item);
    }

    render_verification(&mut out);
    render_footer(&mut out, summary.scan_duration_us);
    out
}

fn render_summary(out: &mut String, findings: &[&Finding]) {
    let critical = findings
        .iter()
        .filter(|finding| finding.severity == Severity::Critical)
        .count();
    let high = findings
        .iter()
        .filter(|finding| finding.severity == Severity::High)
        .count();
    let medium = findings
        .iter()
        .filter(|finding| finding.severity == Severity::Medium)
        .count();
    let _ = writeln!(
        out,
        "## Priority Summary\n\n- Total: {} findings\n- Critical: {critical}\n- High: {high}\n- Medium: {medium}",
        findings.len()
    );
}

fn render_finding_plan(out: &mut String, finding: &Finding, index: usize) {
    let _ = writeln!(
        out,
        "\n### {index}. [{}] {}",
        finding.severity.label(),
        finding.title
    );
    let _ = writeln!(out, "- Rule: `{}`", finding.rule_id);
    if let Some(location) = finding_location(finding) {
        let _ = writeln!(out, "- Location: `{location}`");
    }
    if !finding.description.is_empty() {
        let _ = writeln!(out, "- Why: {}", finding.description);
    }
    if let Some(fix) = finding_recommendation(finding) {
        let _ = writeln!(out, "- Fix: {fix}");
    }
}

fn render_verification(out: &mut String) {
    let _ = writeln!(
        out,
        "\n## Verify\n\n- Run `repopilot scan . --min-severity high` after P0/P1 fixes.\n- Run `repopilot review . --base origin/main --fail-on new-high` before merging.\n- Refresh a baseline only when the remaining findings are accepted technical debt."
    );
}

fn render_footer(out: &mut String, scan_duration_us: u64) {
    let scan_ms = scan_duration_us / 1000;
    let _ = writeln!(out, "\n---\n*Generated by RepoPilot in {scan_ms}ms.*");
}

fn priority_label(finding: &Finding) -> &'static str {
    match priority_rank(finding) {
        0 => "P0 - Immediate risk",
        1 => "P1 - High-impact hardening",
        2 => "P2 - Quality and maintainability",
        _ => "P3 - Backlog cleanup",
    }
}

fn priority_rank(finding: &Finding) -> u8 {
    if finding.severity == Severity::Critical
        || (finding.severity == Severity::High && finding.category == FindingCategory::Security)
    {
        0
    } else if finding.severity == Severity::High {
        1
    } else if finding.severity == Severity::Medium {
        2
    } else {
        3
    }
}

fn category_rank(category: &FindingCategory) -> u8 {
    match category {
        FindingCategory::Security => 0,
        FindingCategory::Architecture => 1,
        FindingCategory::Framework => 2,
        FindingCategory::CodeQuality => 3,
        FindingCategory::Testing => 4,
    }
}

fn finding_recommendation(finding: &Finding) -> Option<&str> {
    lookup_rule_metadata(&finding.rule_id)
        .and_then(|meta| meta.recommendation)
        .or(if finding.description.is_empty() {
            None
        } else {
            Some(finding.description.as_str())
        })
}

fn finding_location(finding: &Finding) -> Option<String> {
    finding.evidence.first().map(|evidence| {
        let path = evidence.path.display().to_string();
        if evidence.line_start > 0 {
            format!("{path}:{}", evidence.line_start)
        } else {
            path
        }
    })
}

fn finding_location_key(finding: &Finding) -> String {
    finding_location(finding).unwrap_or_default()
}
