use crate::findings::types::{Finding, FindingCategory, Severity};
use crate::output::vibe::VibeCategory;
use crate::rules::lookup_rule_metadata;
use crate::scan::types::ScanSummary;
use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;

pub struct HardenOptions {
    pub focus: Option<VibeCategory>,
    pub budget_tokens: usize,
}

impl Default for HardenOptions {
    fn default() -> Self {
        Self {
            focus: None,
            budget_tokens: 4096,
        }
    }
}

pub fn render(summary: &ScanSummary, opts: &HardenOptions) -> String {
    let project_name = summary
        .root_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("project");
    let budget_chars = opts.budget_tokens.saturating_mul(4);

    let findings: Vec<&Finding> = summary
        .findings
        .iter()
        .filter(|finding| {
            opts.focus
                .as_ref()
                .is_none_or(|focus| focus.matches(&finding.category))
        })
        .collect();
    let clusters = finding_clusters(&findings);

    let mut out = String::new();
    let _ = writeln!(out, "# RepoPilot Harden Plan - {project_name}\n");
    let _ = writeln!(
        out,
        "Prioritized remediation plan generated locally from RepoPilot findings. Start at P0 and stop when the remaining risk is acceptable for this release.\n"
    );
    render_summary(&mut out, &findings);

    if findings.is_empty() {
        let _ = writeln!(out, "No findings matched the selected scope.");
        render_footer(&mut out, summary.scan_duration_us);
        return out;
    }

    let mut current_priority = None;
    let content_start = out.len();

    for (index, cluster) in clusters.iter().enumerate() {
        let priority = priority_label(cluster.priority);
        if current_priority != Some(priority) {
            let _ = writeln!(out, "\n## {priority}");
            current_priority = Some(priority);
        }

        let mut item = String::new();
        render_cluster_plan(&mut item, cluster, index + 1);
        if index > 0 && out.len().saturating_sub(content_start) + item.len() > budget_chars {
            let _ = writeln!(out, "\n*[Plan truncated to stay within token budget]*");
            break;
        }
        out.push_str(&item);
    }

    render_verification(&mut out);
    render_footer(&mut out, summary.scan_duration_us);
    out
}

fn render_summary(out: &mut String, findings: &[&Finding]) {
    let critical = findings
        .iter()
        .filter(|finding| finding.severity == Severity::Critical)
        .count();
    let high = findings
        .iter()
        .filter(|finding| finding.severity == Severity::High)
        .count();
    let medium = findings
        .iter()
        .filter(|finding| finding.severity == Severity::Medium)
        .count();
    let _ = writeln!(
        out,
        "## Priority Summary\n\n- Total: {} findings\n- Critical: {critical}\n- High: {high}\n- Medium: {medium}",
        findings.len()
    );
}

fn render_cluster_plan(out: &mut String, cluster: &FindingCluster<'_>, index: usize) {
    let count_note = if cluster.findings.len() > 1 {
        format!(" ({} findings)", cluster.findings.len())
    } else {
        String::new()
    };
    let _ = writeln!(
        out,
        "\n### {index}. [{}] {}{}",
        cluster.severity.label(),
        cluster.title,
        count_note
    );
    let _ = writeln!(out, "- Rule: `{}`", cluster.rule_id);

    let examples = example_locations(&cluster.findings, 3);
    if !examples.is_empty() {
        let _ = writeln!(out, "- Examples: {}", examples.join(", "));
    }

    let first = cluster.findings[0];
    if !first.description.is_empty() {
        let _ = writeln!(out, "- Why: {}", first.description);
    }

    if let Some(fix) = finding_recommendation(first) {
        let _ = writeln!(out, "- Fix: {fix}");
    }
}

fn render_verification(out: &mut String) {
    let _ = writeln!(
        out,
        "\n## Verify\n\n- Run `repopilot scan . --min-severity high` after P0/P1 fixes.\n- Run `repopilot review . --base origin/main --fail-on new-high` before merging.\n- Refresh a baseline only when the remaining findings are accepted technical debt."
    );
}

fn render_footer(out: &mut String, scan_duration_us: u64) {
    let scan_ms = scan_duration_us / 1000;
    let _ = writeln!(out, "\n---\n*Generated by RepoPilot in {scan_ms}ms.*");
}

fn priority_label(priority: u8) -> &'static str {
    match priority {
        0 => "P0 - Immediate risk",
        1 => "P1 - High-impact hardening",
        2 => "P2 - Quality and maintainability",
        _ => "P3 - Backlog cleanup",
    }
}

fn priority_rank(finding: &Finding) -> u8 {
    if finding.severity == Severity::Critical
        || (finding.severity == Severity::High && finding.category == FindingCategory::Security)
    {
        0
    } else if finding.severity == Severity::High {
        1
    } else if finding.severity == Severity::Medium {
        2
    } else {
        3
    }
}

fn category_rank(category: &FindingCategory) -> u8 {
    match category {
        FindingCategory::Security => 0,
        FindingCategory::Architecture => 1,
        FindingCategory::Framework => 2,
        FindingCategory::CodeQuality => 3,
        FindingCategory::Testing => 4,
    }
}

fn finding_recommendation(finding: &Finding) -> Option<&str> {
    lookup_rule_metadata(&finding.rule_id)
        .and_then(|meta| meta.recommendation)
        .or(if finding.description.is_empty() {
            None
        } else {
            Some(finding.description.as_str())
        })
}

fn finding_location(finding: &Finding) -> Option<String> {
    finding.evidence.first().map(|evidence| {
        let path = evidence.path.display().to_string();
        if evidence.line_start > 0 {
            format!("{path}:{}", evidence.line_start)
        } else {
            path
        }
    })
}

struct FindingCluster<'a> {
    title: &'a str,
    rule_id: &'a str,
    severity: Severity,
    priority: u8,
    category_rank: u8,
    findings: Vec<&'a Finding>,
}

fn finding_clusters<'a>(findings: &'a [&'a Finding]) -> Vec<FindingCluster<'a>> {
    let mut by_rule: BTreeMap<&str, Vec<&Finding>> = BTreeMap::new();
    for finding in findings.iter().copied() {
        by_rule.entry(&finding.rule_id).or_default().push(finding);
    }

    let mut clusters = by_rule
        .into_values()
        .filter_map(|mut group| {
            group.sort_by(|left, right| {
                right
                    .severity
                    .cmp(&left.severity)
                    .then_with(|| finding_location(left).cmp(&finding_location(right)))
            });
            let first = group.first().copied()?;
            let title = cluster_title(first, group.len());
            Some(FindingCluster {
                title,
                rule_id: first.rule_id.as_str(),
                severity: group
                    .iter()
                    .map(|finding| finding.severity)
                    .max()
                    .unwrap_or(first.severity),
                priority: group
                    .iter()
                    .map(|finding| priority_rank(finding))
                    .min()
                    .unwrap_or_else(|| priority_rank(first)),
                category_rank: category_rank(&first.category),
                findings: group,
            })
        })
        .collect::<Vec<_>>();

    clusters.sort_by(|left, right| {
        left.priority
            .cmp(&right.priority)
            .then_with(|| right.severity.cmp(&left.severity))
            .then_with(|| left.category_rank.cmp(&right.category_rank))
            .then_with(|| right.findings.len().cmp(&left.findings.len()))
            .then_with(|| left.rule_id.cmp(right.rule_id))
    });
    clusters
}

fn cluster_title(finding: &Finding, count: usize) -> &str {
    if count > 1 {
        lookup_rule_metadata(&finding.rule_id)
            .map(|metadata| metadata.title)
            .unwrap_or(finding.rule_id.as_str())
    } else {
        finding.title.as_str()
    }
}

fn example_locations(findings: &[&Finding], limit: usize) -> Vec<String> {
    findings
        .iter()
        .filter_map(|finding| finding_location(finding))
        .take(limit)
        .map(|location| format!("`{location}`"))
        .collect()
}
