pub mod ai_context;
pub mod ai_plan;
pub mod baseline;
pub mod cache;
pub mod cache_inspect;
pub mod compare;
mod dispatch;
pub mod doctor;
pub mod explain;
pub mod feedback;
pub(crate) mod filters;
pub(crate) mod focus;
pub mod graph;
pub mod init;
pub mod knowledge;
mod llm;
pub mod mcp;
pub(crate) mod product_scan;
mod progress;
pub mod prompt;
pub mod review;
pub mod rules;
pub mod scan;
pub(crate) mod scan_config;
pub mod snapshot;

pub use dispatch::{CliExit, EXIT_FINDINGS, EXIT_RUNTIME, EXIT_USAGE, run};
