#!/usr/bin/env python3
"""Integrity corpus: public pull requests that modify test code (v0.24 Phase D).

Samples merged PRs from coding-agent accounts or markers and human-authored PRs
from the same repositories, pins them by SHA in tests/integrity/manifest.toml,
caches their test and gate file patches under the gitignored
`.integrity-corpus/`, prints them for blinded labeling, and reports prevalence
from tests/integrity/labels.toml.

    python3 scripts/integrity_corpus.py sample   # needs `gh` auth; writes manifest
    python3 scripts/integrity_corpus.py fetch    # caches patches for the manifest
    python3 scripts/integrity_corpus.py show ID  # test/gate hunks for labeling
    python3 scripts/integrity_corpus.py report   # prevalence with Wilson intervals
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path

import integrity_corpus_github as gh
import integrity_corpus_report as report
from integrity_corpus_paths import is_gate_file, is_test_file

REPO_ROOT = Path(__file__).resolve().parent.parent
CORPUS_DIR = REPO_ROOT / "tests" / "integrity"
MANIFEST = CORPUS_DIR / "manifest.toml"
LABELS = CORPUS_DIR / "labels.toml"
CACHE = REPO_ROOT / ".integrity-corpus"

WINDOW = ("2026-06-01", "2026-09-28")
AGENT_QUERIES = {
    "copilot": "author:app/copilot-swe-agent",
    "devin": "author:app/devin-ai-integration",
    "jules": "author:app/google-labs-jules",
    "claude-code": '"Generated with Claude Code" in:body',
    "codex": "label:codex",
}
MIN_STARS = 100
MAX_FILES = 60
PER_REPO = 2


def load_manifest() -> list[dict]:
    if not MANIFEST.exists():
        return []
    return tomllib.loads(MANIFEST.read_text())["pr"]


def write_manifest(entries: list[dict]) -> None:
    lines = [
        "# Integrity corpus manifest (v0.24 Phase D). Generated by",
        "# `scripts/integrity_corpus.py sample`; pinned by SHA. Do not edit by hand.",
        f'# Window: merged PRs created {WINDOW[0]}..{WINDOW[1]}; repos >= {MIN_STARS} stars;',
        f"# <= {MAX_FILES} changed files; >= 1 modified or removed test file.",
        "",
    ]
    for entry in entries:
        lines.append("[[pr]]")
        for key in ("id", "group", "agent", "repo", "number", "base_sha", "head_sha", "language", "created"):
            value = entry[key]
            lines.append(f"{key} = {json.dumps(value)}")
        lines.append("")
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text("\n".join(lines))


def qualifies(repo: str, number: int, stars_cache: dict[str, int]) -> dict | None:
    if repo not in stars_cache:
        stars_cache[repo] = gh.repo_stars(repo)
    if stars_cache[repo] < MIN_STARS:
        return None
    files = gh.pr_files(repo, number)
    if len(files) > MAX_FILES:
        return None
    touched = [f for f in files if f["status"] in ("modified", "removed", "renamed") and is_test_file(f)]
    if not touched:
        return None
    exts = sorted({Path(f["filename"]).suffix.lstrip(".") for f in touched})
    pr = gh.pr_meta(repo, number)
    return {
        "repo": repo,
        "number": number,
        "base_sha": pr["base"]["sha"],
        "head_sha": pr["head"]["sha"],
        "language": ",".join(exts),
        "created": pr["created_at"][:10],
        "user_type": pr["user"]["type"],
        "body": pr.get("body") or "",
    }


def sample(per_agent: int) -> None:
    stars: dict[str, int] = {}
    picked: list[dict] = []
    repos_used: dict[tuple[str, str], int] = {}
    for agent, qualifier in AGENT_QUERIES.items():
        count = 0
        for repo, number in gh.search_prs(qualifier, WINDOW):
            if count >= per_agent:
                break
            if repos_used.get(("agent", repo), 0) >= PER_REPO:
                continue
            entry = qualifies(repo, number, stars)
            if entry is None:
                continue
            entry.update(group="agent", agent=agent)
            picked.append(entry)
            repos_used[("agent", repo)] = repos_used.get(("agent", repo), 0) + 1
            count += 1
            print(f"agent/{agent}: {repo}#{number}", file=sys.stderr)
    agent_repos = sorted({e["repo"] for e in picked})
    for repo in agent_repos:
        count = 0
        for number in gh.search_repo_human_prs(repo, WINDOW, list(AGENT_QUERIES.values())):
            if count >= PER_REPO:
                break
            entry = qualifies(repo, number, stars)
            if entry is None or entry["user_type"] != "User" or gh.has_agent_marker(entry["body"]):
                continue
            entry.update(group="human", agent="none")
            picked.append(entry)
            count += 1
            print(f"human: {repo}#{number}", file=sys.stderr)
    picked.sort(key=lambda e: (e["group"], e["repo"], e["number"]))
    for index, entry in enumerate(picked, start=1):
        entry["id"] = f"ic-{index:03d}"
    write_manifest(picked)
    print(f"wrote {len(picked)} PRs to {MANIFEST.relative_to(REPO_ROOT)}")


def fetch() -> None:
    CACHE.mkdir(exist_ok=True)
    for entry in load_manifest():
        path = CACHE / f"{entry['id']}.json"
        if path.exists():
            continue
        files = gh.pr_files(entry["repo"], entry["number"])
        meta = gh.pr_meta(entry["repo"], entry["number"])
        keep = [f for f in files if is_test_file(f) or is_gate_file(f["filename"])]
        path.write_text(json.dumps({"title": meta["title"], "files": keep, "all_files": [f["filename"] for f in files]}))
        print(f"cached {entry['id']}", file=sys.stderr)


def show(corpus_id: str) -> None:
    entry = next((e for e in load_manifest() if e["id"] == corpus_id), None)
    if entry is None:
        sys.exit(f"unknown corpus id {corpus_id}")
    data = json.loads((CACHE / f"{corpus_id}.json").read_text())
    print(f"# {corpus_id} {entry['repo']}#{entry['number']} — {data['title']}")
    print(f"# changed files: {len(data['all_files'])}; non-test: " + ", ".join(f for f in data["all_files"] if not any(f == k["filename"] for k in data["files"]))[:600])
    for f in data["files"]:
        print(f"\n## {f['status']} {f['filename']} (+{f['additions']} -{f['deletions']})")
        print(f.get("patch") or "(patch unavailable: file too large)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("sample")
    s.add_argument("--per-agent", type=int, default=20)
    sub.add_parser("fetch")
    sh = sub.add_parser("show")
    sh.add_argument("id")
    sub.add_parser("report")
    args = parser.parse_args()
    if args.cmd == "sample":
        sample(args.per_agent)
    elif args.cmd == "fetch":
        fetch()
    elif args.cmd == "show":
        show(args.id)
    else:
        print(report.render(load_manifest(), tomllib.loads(LABELS.read_text()) if LABELS.exists() else {}))


if __name__ == "__main__":
    main()
