#!/usr/bin/env python3
"""Integrity corpus: public pull requests that modify test code (v0.24 Phase D).

Samples merged PRs from coding-agent accounts or markers and human-authored PRs
from the same repositories, pins them by SHA in tests/integrity/manifest.toml,
caches their test and gate file patches under the gitignored
`.integrity-corpus/`, prints them for blinded labeling, and reports prevalence
from tests/integrity/labels.toml.

    python3 scripts/integrity_corpus.py sample   # needs `gh` auth; writes manifest
    python3 scripts/integrity_corpus.py fetch    # caches patches for the manifest
    python3 scripts/integrity_corpus.py show ID  # test/gate hunks for labeling
    python3 scripts/integrity_corpus.py evaluate # run a RepoPilot build per PR
    python3 scripts/integrity_corpus.py report   # prevalence and catches, Wilson intervals
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

import integrity_corpus_eval as evaluation
import integrity_corpus_github as gh
import integrity_corpus_report as report
from integrity_corpus_paths import is_gate_file, is_test_file

REPO_ROOT = Path(__file__).resolve().parent.parent
CORPUS_DIR = REPO_ROOT / "tests" / "integrity"
MANIFEST = CORPUS_DIR / "manifest.toml"
CLOSED_MANIFEST = CORPUS_DIR / "manifest-closed.toml"
HOLDOUT_MANIFEST = CORPUS_DIR / "manifest-holdout.toml"
LABELS = CORPUS_DIR / "labels.toml"
CACHE = REPO_ROOT / ".integrity-corpus"

WINDOW = ("2026-06-01", "2026-09-28")
# Held-out sample, drawn after the detectors were tuned on the main corpus.
HOLDOUT_WINDOW = ("2026-03-01", "2026-05-31")
AGENT_QUERIES = {
    "copilot": "author:app/copilot-swe-agent",
    "devin": "author:app/devin-ai-integration",
    "jules": "author:app/google-labs-jules",
    "claude-code": '"Generated with Claude Code" in:body',
    "codex": "label:codex",
}
MIN_STARS = 100
MAX_FILES = 60
PER_REPO = 2
SHOW_LINES = 160
STATUS = {"ADDED": "added", "DELETED": "removed", "MODIFIED": "modified", "RENAMED": "renamed", "COPIED": "added", "CHANGED": "modified"}


def load_manifest() -> list[dict]:
    entries = []
    for path in (MANIFEST, HOLDOUT_MANIFEST, CLOSED_MANIFEST):
        if path.exists():
            entries.extend(tomllib.loads(path.read_text())["pr"])
    return entries


def write_manifest(
    entries: list[dict], path: Path = MANIFEST, scope: str = "merged PRs", window: tuple[str, str] = WINDOW
) -> None:
    lines = [
        "# Integrity corpus manifest (v0.24 Phase D). Generated by",
        "# `scripts/integrity_corpus.py sample`; pinned by SHA. Do not edit by hand.",
        f"# Window: {scope} created {window[0]}..{window[1]}; repos >= {MIN_STARS} stars;",
        f"# <= {MAX_FILES} changed files; >= 1 modified or removed test file.",
        "",
    ]
    for entry in entries:
        lines.append("[[pr]]")
        for key in ("id", "group", "agent", "repo", "number", "base_sha", "head_sha", "language", "created"):
            value = entry[key]
            lines.append(f"{key} = {json.dumps(value)}")
        lines.append("")
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def qualifies(node: dict) -> dict | None:
    repo = node["repository"]
    if repo["isFork"] or repo["isArchived"] or repo["isPrivate"] or repo["stargazerCount"] < MIN_STARS:
        return None
    if not 0 < node["changedFiles"] <= MAX_FILES:
        return None
    files = [{"filename": f["path"], "status": STATUS[f["changeType"]]} for f in node["files"]["nodes"]]
    touched = [f for f in files if f["status"] in ("modified", "removed", "renamed") and is_test_file(f)]
    if not touched:
        return None
    return {
        "repo": repo["nameWithOwner"],
        "number": node["number"],
        "base_sha": node["baseRefOid"],
        "head_sha": node["headRefOid"],
        "language": ",".join(sorted({Path(f["filename"]).suffix.lstrip(".") for f in touched})),
        "created": node["createdAt"][:10],
        "user_type": (node.get("author") or {}).get("__typename", ""),
        "body": node.get("body") or "",
    }


def sample(per_agent: int, holdout: bool = False) -> None:
    """Resumable: progress is appended to the gitignored cache as it is found,
    so a rate-limit stop loses nothing already sampled. `holdout` samples an
    earlier window into its own manifest with `ih-` ids."""
    window = HOLDOUT_WINDOW if holdout else WINDOW
    CACHE.mkdir(exist_ok=True)
    progress = CACHE / ("sample-holdout-progress.jsonl" if holdout else "sample-progress.jsonl")
    done_windows: set[tuple[str, str]] = set()
    picked: list[dict] = []
    if progress.exists():
        for line in progress.read_text().splitlines():
            record = json.loads(line)
            if record["type"] == "window":
                done_windows.add((record["agent"], record["span"]))
            else:
                picked.append(record["entry"])

    def remember(record: dict) -> None:
        with progress.open("a") as handle:
            handle.write(json.dumps(record) + "\n")

    seen = {(e["repo"], e["number"]) for e in picked}
    for agent, qualifier in AGENT_QUERIES.items():
        count = sum(1 for e in picked if e["agent"] == agent)
        for span in gh.windows(window, 2):
            if count >= per_agent:
                break
            if (agent, span) in done_windows:
                continue
            for node in gh.search_pr_nodes(f"is:pr is:merged review:approved {qualifier} created:{span}", pages=3):
                entry = qualifies(node)
                if entry is None or (entry["repo"], entry["number"]) in seen:
                    continue
                if sum(1 for e in picked if e["group"] == "agent" and e["repo"] == entry["repo"]) >= PER_REPO:
                    continue
                entry.update(group="agent", agent=agent)
                picked.append(entry)
                seen.add((entry["repo"], entry["number"]))
                remember({"type": "entry", "entry": entry})
                count += 1
                print(f"agent/{agent}: {entry['repo']}#{entry['number']}", file=sys.stderr, flush=True)
                if count >= per_agent:
                    break
            remember({"type": "window", "agent": agent, "span": span})
    for repo in sorted({e["repo"] for e in picked if e["group"] == "agent"}):
        if (f"human:{repo}", "all") in done_windows:
            continue
        count = sum(1 for e in picked if e["group"] == "human" and e["repo"] == repo)
        for node in gh.search_repo_human_prs(repo, window, list(AGENT_QUERIES.values())):
            if count >= PER_REPO:
                break
            entry = qualifies(node)
            if entry is None or entry["user_type"] != "User" or gh.has_agent_marker(entry["body"]):
                continue
            if (entry["repo"], entry["number"]) in seen:
                continue
            entry.update(group="human", agent="none")
            picked.append(entry)
            seen.add((entry["repo"], entry["number"]))
            remember({"type": "entry", "entry": entry})
            count += 1
            print(f"human: {repo}#{entry['number']}", file=sys.stderr, flush=True)
        remember({"type": "window", "agent": f"human:{repo}", "span": "all"})
    picked.sort(key=lambda e: (e["group"], e["repo"], e["number"]))
    prefix, path = ("ih", HOLDOUT_MANIFEST) if holdout else ("ic", MANIFEST)
    for index, entry in enumerate(picked, start=1):
        entry["id"] = f"{prefix}-{index:03d}"
    write_manifest(picked, path, "merged PRs", window)
    print(f"wrote {len(picked)} PRs to {path.relative_to(REPO_ROOT)}")


def fetch() -> None:
    CACHE.mkdir(exist_ok=True)
    for entry in load_manifest():
        path = CACHE / f"{entry['id']}.json"
        if path.exists():
            continue
        files = gh.pr_files(entry["repo"], entry["number"])
        meta = gh.pr_meta(entry["repo"], entry["number"])
        keep = [f for f in files if is_test_file(f) or is_gate_file(f["filename"])]
        suppressions = [
            {"file": f["filename"], "line": line[1:].strip()[:200]}
            for f in files
            if f not in keep
            for line in (f.get("patch") or "").splitlines()
            if line.startswith("+") and not line.startswith("+++") and SUPPRESSION_VOCABULARY.search(line)
        ]
        path.write_text(
            json.dumps(
                {
                    "title": meta["title"],
                    "files": keep,
                    "all_files": [f["filename"] for f in files],
                    "source_suppressions": suppressions,
                }
            )
        )
        print(f"cached {entry['id']}", file=sys.stderr)


# Added lines in files outside the labeling view that look like a lint, type,
# or coverage suppression; shown so suppression-added labels cover every file.
SUPPRESSION_VOCABULARY = re.compile(
    r"noqa|nolint|eslint-disable|ts-ignore|ts-expect-error|ts-nocheck|type:\s*ignore|pragma:\s*no cover"
    r"|pylint:\s*disable|mypy:|pyright:\s*ignore|#!?\[(allow|expect)\(|biome-ignore|tslint:disable"
    r"|istanbul ignore|c8 ignore|NOSONAR|@SuppressWarnings|nosec|lint:ignore",
    re.IGNORECASE,
)

ADDITIVE_VOCABULARY = re.compile(
    r"skip|\.only|fit\(|fdescribe|xfail|xit\(|todo|ignore|noqa|nolint|eslint-disable|ts-expect|ts-nocheck"
    r"|allow\(|pragma|continue-on-error|allow_failure|fail_under|threshold|strict|deselect|\|\| true|exit 0",
    re.IGNORECASE,
)


def show(corpus_id: str, compact: bool = False) -> None:
    entry = next((e for e in load_manifest() if e["id"] == corpus_id), None)
    if entry is None:
        sys.exit(f"unknown corpus id {corpus_id}")
    data = json.loads((CACHE / f"{corpus_id}.json").read_text())
    print(f"# {corpus_id} [{entry['group']}/{entry['agent']}] {entry['repo']}#{entry['number']} — {data['title']}")
    others = [f for f in data["all_files"] if not any(f == k["filename"] for k in data["files"])]
    print(f"# other changed files ({len(others)}): " + ", ".join(others)[:400])
    if "source_suppressions" in data:
        found = data["source_suppressions"]
        print(f"# added suppression-like lines in other files: {len(found)}")
        for item in found[:20]:
            print(f"#   {item['file']}: {item['line']}")
    for f in data["files"]:
        print(f"## {f['status']} {f['filename']} (+{f['additions']} -{f['deletions']})")
        patch = (f.get("patch") or "(patch unavailable: file too large)").splitlines()
        if compact:
            patch = compact_patch(patch)
        print("\n".join(patch[:SHOW_LINES]))
        if len(patch) > SHOW_LINES:
            print(f"... ({len(patch) - SHOW_LINES} more lines not shown)")


def compact_patch(lines: list[str]) -> list[str]:
    """Hunks with removals in full; additive hunks reduced to lines that use
    skip/focus/suppression/gate vocabulary. Context lines are dropped."""
    hunks, current = [], []
    for line in lines:
        if line.startswith("@@") and current:
            hunks.append(current)
            current = []
        current.append(line)
    if current:
        hunks.append(current)
    out, hidden = [], 0
    for hunk in hunks:
        changed = [line for line in hunk[1:] if line.startswith(("+", "-"))]
        if any(line.startswith("-") for line in changed):
            out.append(hunk[0])
            out.extend(changed)
        else:
            flagged = [line for line in changed if ADDITIVE_VOCABULARY.search(line)]
            if flagged:
                out.append(hunk[0] + " (additive; vocabulary lines only)")
                out.extend(flagged)
            else:
                hidden += 1
    if hidden:
        out.append(f"({hidden} purely additive hunk(s) without skip/suppression/gate vocabulary hidden)")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("sample")
    s.add_argument("--per-agent", type=int, default=20)
    s.add_argument("--closed", action="store_true", help="agent PRs closed without merge, into manifest-closed.toml")
    s.add_argument("--holdout", action="store_true", help="merged PRs from an earlier window, into manifest-holdout.toml")
    sub.add_parser("fetch")
    sh = sub.add_parser("show")
    sh.add_argument("ids", nargs="+")
    sh.add_argument("--compact", action="store_true")
    sub.add_parser("report")
    ev = sub.add_parser("evaluate")
    ev.add_argument("--bin", type=Path, default=REPO_ROOT / "target" / "release" / "repopilot")
    ev.add_argument("--prefix", default="", help="only ids starting with this, e.g. ih- (keeps unlabeled splits blind)")
    args = parser.parse_args()
    if args.cmd == "sample" and args.closed:
        import integrity_corpus_closed

        integrity_corpus_closed.sample_closed(args.per_agent)
    elif args.cmd == "sample":
        sample(args.per_agent, holdout=args.holdout)
    elif args.cmd == "fetch":
        fetch()
    elif args.cmd == "show":
        for corpus_id in args.ids:
            show(corpus_id, compact=args.compact)
            print()
    elif args.cmd == "evaluate":
        evaluation.evaluate([e for e in load_manifest() if e["id"].startswith(args.prefix)], CACHE, args.bin)
    else:
        results = {
            path.stem: json.loads(path.read_text()) for path in sorted((CACHE / "results").glob("*.json"))
        }
        labels = tomllib.loads(LABELS.read_text()) if LABELS.exists() else {}
        print(report.render(load_manifest(), labels, results))


if __name__ == "__main__":
    main()
