#!/usr/bin/env python3
"""Generate the v0.24 release scorecard from committed evidence.

Every number comes from a committed file: the evidence ledger, the risk-v4
calibration, the integrity review fixtures, the integrity corpus labels and
results, the zoo snapshots, the released-report compatibility manifest, and
the recorded performance and publication evidence. Nothing is cloned, built,
or fetched, so the release contract can check that the scorecard is current.

    python3 scripts/release_scorecard.py            # check; exit 1 when stale
    python3 scripts/release_scorecard.py --write    # regenerate
    python3 scripts/release_scorecard.py --measure  # record performance, then write
"""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
import tomllib
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import integrity_corpus as corpus  # noqa: E402
import integrity_corpus_report as corpus_report  # noqa: E402
import release_scorecard_sections as sections  # noqa: E402

SCORECARD = ROOT / "docs" / "engineering" / "v0.24-release-scorecard.md"
PERFORMANCE = ROOT / "docs" / "engineering" / "v0.24-performance.json"
PUBLICATION = ROOT / "docs" / "engineering" / "v0.24-publication.json"
BANNER = (
    "<!-- @generated by scripts/release_scorecard.py from committed evidence — do not edit by hand. -->\n"
    "<!-- Regenerate with `python3 scripts/release_scorecard.py --write`. -->"
)


def corpus_lines() -> list[str]:
    """Held-out precision (blind labels) and weakening before and after review."""
    manifest = corpus.load_manifest()
    labels = tomllib.loads(corpus.LABELS.read_text())
    by_id = {entry["id"]: entry for entry in labels.get("label", [])}
    summary = json.loads(corpus.RESULTS.read_text())
    results = {
        corpus_id: {**entry, "signals": [{"kind": kind} for kind in entry["signals"]]}
        for corpus_id, entry in summary.items()
    }
    holdout = [entry for entry in manifest if entry["id"].startswith("ih-")]
    catches = corpus_report.catches(holdout, by_id, results, "held-out, blind labels, evaluated once")
    lines = [line for line in catches][1:]
    lines += [
        "",
        "### Unexplained weakening, blind and after maintainer review",
        "",
        "| Split | Group | Blind | After review |",
        "|---|---|---|---|",
    ]
    for prefix, split in (("ic-", "development"), ("ih-", "held-out"), ("icc-", "closed")):
        entries = [entry for entry in manifest if entry["id"].startswith(prefix) and entry["id"] in by_id]
        for group in sorted({entry["group"] for entry in entries}):
            members = [by_id[entry["id"]] for entry in entries if entry["group"] == group]
            blind = sum(1 for label in members if label["verdict"] == "weakened")
            reviewed = sum(
                1 for label in members if label.get("reviewed_verdict", label["verdict"]) == "weakened"
            )
            lines.append(f"| {split} | {group} | {blind}/{len(members)} | {reviewed}/{len(members)} |")
    lines += [
        "",
        "Kinds were not changed by the review, so the precision table uses blind labels.",
        "Full tables: [integrity corpus report](../../tests/integrity/REPORT.md).",
    ]
    return lines


def render() -> str:
    performance = json.loads(PERFORMANCE.read_text()) if PERFORMANCE.exists() else None
    publication = json.loads(PUBLICATION.read_text()) if PUBLICATION.exists() else None
    parts = [
        "# v0.24 Release Scorecard",
        "",
        BANNER,
        "",
        "One page of release evidence for RepoPilot 0.24 (Honest Green). Each section",
        "is regenerated from the committed file it names; the release contract fails",
        "when this page is stale.",
        "",
        "## Release status",
        "",
        *sections.ledger_lines(ROOT / "docs" / "engineering" / "v0.24-evidence-ledger.md"),
        "",
        "## Risk calibration (Phase A)",
        "",
        *sections.calibration_lines(ROOT / "docs" / "engineering" / "risk-v4-calibration.md"),
        "",
        "## Integrity fixtures (Phase C)",
        "",
        *sections.fixture_lines(ROOT / "tests" / "fixtures" / "review" / "integrity"),
        "",
        "## Integrity corpus (Phase D)",
        "",
        *corpus_lines(),
        "",
        "## Zoo scan (integrity signals are review-only)",
        "",
        *sections.zoo_lines(ROOT / "tests" / "zoo"),
        "",
        "## Report compatibility",
        "",
        *sections.compatibility_lines(ROOT / "tests" / "fixtures" / "reports" / "releases" / "manifest.json"),
        "",
        "## Performance budgets",
        "",
        *sections.performance_lines(ROOT / "scripts", performance),
        "",
        "## Publication",
        "",
        *sections.publication_lines(publication),
    ]
    return "\n".join(parts) + "\n"


def measure() -> None:
    """Run the changed-review performance gate and record its JSON output."""
    run = subprocess.run(
        ["node", str(ROOT / "scripts" / "check-review-performance.js")],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    start = run.stdout.find("{")
    if start < 0:
        sys.exit(f"performance gate printed no JSON:\n{run.stderr[-2000:]}")
    record = {
        "measured_on": date.today().isoformat(),
        "platform": f"{platform.system().lower()}-{platform.machine()}",
        "gate_passed": run.returncode == 0,
        "results": json.loads(run.stdout[start:]),
    }
    PERFORMANCE.write_text(json.dumps(record, indent=2) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="regenerate the scorecard")
    parser.add_argument("--measure", action="store_true", help="record performance first, then write")
    args = parser.parse_args()
    if args.measure:
        measure()
    rendered = render()
    if args.write or args.measure:
        SCORECARD.write_text(rendered)
        print(f"wrote {SCORECARD.relative_to(ROOT)}")
        return
    if not SCORECARD.exists() or SCORECARD.read_text() != rendered:
        sys.exit(f"{SCORECARD.relative_to(ROOT)} is stale; run `python3 scripts/release_scorecard.py --write`")
    print("release scorecard is current")


if __name__ == "__main__":
    main()
